@startuml
title KursachSPZ — full class diagram
class "PowerMonitor" as C_0003680149248695565992
class C_0003680149248695565992 {
+PowerMonitor(QObject * parent = nullptr) : void
..
-checkBattery() : void
+metaObject() const : const QMetaObject *
+processWindowsMessage(UINT msg, WPARAM wParam) : void
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
+start() : void
+stop() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-m_lastBatteryPercent : int
-m_timer : QTimer *
-m_wasCharging : bool
{static} +staticMetaObject : const QMetaObject
}
class "DatabaseManager" as C_0006040296495016557319
class C_0006040296495016557319 {
-DatabaseManager(QObject * parent = nullptr) : void
..
+initDatabase() : bool
{static} +instance() : DatabaseManager *
+logClipboard(const QString & text) : void
+logEvent(const QString & type, const QString & description) : void
+logKey(const QString & key) : void
+logUsb(const QString & action, const QString & deviceName) : void
+metaObject() const : const QMetaObject *
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-m_db : QSqlDatabase
{static} -m_instance : DatabaseManager *
{static} +staticMetaObject : const QMetaObject
}
class "ProcessInfo" as C_0001767362958478954178
class C_0001767362958478954178 {
__
+name : QString
+startTime : QDateTime
}
class "QMap<DWORD,ProcessInfo>" as C_0000784021463933809475
class C_0000784021463933809475 {
__
}
class "AppMonitor" as C_0007887141664541954018
class C_0007887141664541954018 {
+AppMonitor(QObject * parent = nullptr) : void
..
-checkProcesses(bool silentMode = false) : void
+metaObject() const : const QMetaObject *
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
+start() : void
+stop() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-m_runningProcesses : QMap<DWORD,ProcessInfo>
-m_timer : QTimer *
{static} +staticMetaObject : const QMetaObject
}
class "QMap<int,double>" as C_0002626946978745399994
class C_0002626946978745399994 {
__
}
class "ActivityChart" as C_0017327431590948374388
class C_0017327431590948374388 {
+ActivityChart(QWidget * parent = nullptr) : void
..
+metaObject() const : const QMetaObject *
#paintEvent(QPaintEvent * event) : void
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
+setData(const QMap<int,double> & data) : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-m_data : QMap<int,double>
{static} +staticMetaObject : const QMetaObject
}
class "UsbMonitor" as C_0005048182647798814005
class C_0005048182647798814005 {
+UsbMonitor(QObject * parent = nullptr) : void
..
+metaObject() const : const QMetaObject *
+processDeviceChange(WPARAM wParam, LPARAM lParam) : void
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
+start() : void
+stop() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-m_lastAction : QString
-m_lastDevice : QString
-m_lastTime : QDateTime
-m_running : bool
{static} +staticMetaObject : const QMetaObject
}
class "InputMonitor" as C_0010617902402347083579
class C_0010617902402347083579 {
+InputMonitor(QObject * parent = nullptr) : void
..
{static} +KeyboardProc(int nCode, WPARAM wParam, LPARAM lParam) : LRESULT
+metaObject() const : const QMetaObject *
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
+start() : void
+stop() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-m_hKeyboardHook : HHOOK
{static} +staticMetaObject : const QMetaObject
}
class "ClipboardMonitor" as C_0006682767790515874693
class C_0006682767790515874693 {
+ClipboardMonitor(QObject * parent = nullptr) : void
..
-checkClipboard() : void
+metaObject() const : const QMetaObject *
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
+start() : void
+stop() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-m_active : bool
-m_lastClipboardText : QString
{static} +staticMetaObject : const QMetaObject
}
class "MainWindow" as C_0002900986228388971956
class C_0002900986228388971956 {
+MainWindow(QWidget * parent = nullptr) : void
+~MainWindow() : void
..
+metaObject() const : const QMetaObject *
-nativeEvent(const QByteArray & eventType, void * message, qintptr * result) : bool
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
-refreshLogs() : void
-startMonitoring() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
-updateHeatmap() : void
__
-m_activityChart : ActivityChart *
-m_appMon : AppMonitor *
-m_clipMon : ClipboardMonitor *
-m_inputMon : InputMonitor *
-m_powerMon : PowerMonitor *
-m_powerTable : QTableWidget *
-m_usbMon : UsbMonitor *
{static} +staticMetaObject : const QMetaObject
-ui : Ui::MainWindow *
}
C_0006040296495016557319 --> C_0006040296495016557319 : -m_instance
C_0000784021463933809475 ..> C_0001767362958478954178
C_0007887141664541954018 o-- C_0000784021463933809475 : -m_runningProcesses
C_0017327431590948374388 o-- C_0002626946978745399994 : -m_data
C_0002900986228388971956 --> C_0017327431590948374388 : -m_activityChart
C_0002900986228388971956 --> C_0007887141664541954018 : -m_appMon
C_0002900986228388971956 --> C_0010617902402347083579 : -m_inputMon
C_0002900986228388971956 --> C_0005048182647798814005 : -m_usbMon
C_0002900986228388971956 --> C_0006682767790515874693 : -m_clipMon
C_0002900986228388971956 --> C_0003680149248695565992 : -m_powerMon
skinparam classBackgroundColor #FAFAFA
skinparam classBorderColor #888888
skinparam ArrowColor #555555
skinparam linetype ortho

'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
